### ISSUE TITLE
Bot shows "undefined" instead of nickname if Telegram user have no nickname

### ISSUE THREAD

**Issue by ForNeVeR** [jt3k/chat-linker#13]
From XMPP room:
> &lt;tg> <@undefined> как реализовать работу 9 работ практических на одной странцы ?

At the same time in Telegram I can see the name of the man who wrote that, but he somehow has no nickname:

![image](https://cloud.githubusercontent.com/assets/92793/21225376/1c92a3fe-c303-11e6-9fe2-2018bbcd9bc5.png)

**Comment by jt3k** [comment]
still relevant?

I close the issue. and will open again if the problem persists

**Comment by Minoru** [comment]
Bumped into this today in codingteam@conference.org.ru; see [the log](https://codingteam.org.ru/_logs/codingteam@conference.jabber.ru/2017/03/26.html#15:33:02.963514). Maybe Codingteam just didn't deploy your fix? @ForNeVeR should know.

**Comment by ForNeVeR** [comment]
@jt3k probably it was fixed in some private branch? I can clearly see that your bot instance is fixed, but mine (cloned from the latest `master` commit) doesn't.

**Comment by jt3k** [comment]
now is the time to check it out!

**Comment by jt3k** [comment]
fixed

**Comment by ForNeVeR** [comment]
Yep, I can confirm that this is fixed. Thanks.
