### ISSUE TITLE
Sometimes bot loses connection to XMPP and won't restore it

### ISSUE THREAD

**Issue by ForNeVeR** [jt3k/chat-linker#17]
Sometimes bot is disconnected from XMPP, and it restores the connection only after any message to Telegram. I suspect that something's wrong with client timeouts; please make it configurable.

**Comment by ForNeVeR** [comment]
Probably we need to enable periodic XMPP ping somehow. It's usually included as an option into XMPP library.

**Comment by ForNeVeR** [comment]
Well, it was fixed by my PR.

**Comment by jt3k** [comment]
😋
