### ISSUE TITLE
Option to make Telegram messages more compact

### ISSUE THREAD

**Issue by ForNeVeR** [jt3k/chat-linker#24]
Currently Telegram messages aren't very compact: they look like
> **username**
> Message body.

I suggest to add an **option** to change the format to more compact, such as
> \<**username**> Message body.

**Comment by jt3k** [comment]
Good idea!

**Comment by jt3k** [comment]
Now you can specify the `messageTemplate` property in the config to change the message template for the jabber and the telegram

```json
{
  "jabber": {
    "...": "...",
    "messageTemplate": "<{name}> {message}"
  }
}
```
