### ISSUE TITLE
Possibility of sending stickers.

### ISSUE THREAD

**Issue by jt3k** [jt3k/chat-linker#39]
Since there is no easy way to transfer stickers from telegram to jabber, I suggest sending emoji bound to this sticker.

example:
In jabber-side sticker can look like here
```
<@vasya> sends sticker: 🍷🍻🎶
```

**Comment by unauthorized-401** [comment]
Please merge https://github.com/jt3k/chat-linker/pull/40

**Comment by ForNeVeR** [comment]
Done.
