### ISSUE TITLE
Author of message forwarded from a channel doesn't displayed on jabber side

### ISSUE THREAD

**Issue by Bannerets** [jt3k/chat-linker#52]

**Comment by ForNeVeR** [comment]
Usually this happens when someone forwards multiple messages simultaneously. In that case, XMPP server won't allow the bot to post too many messages at a time. See #34 for that case discussion.

**Comment by Bannerets** [comment]
@ForNeVeR @fornever this happens because author of the message, forwarded from channel, is in the forward_from_chat field, and not in the forward_from.
